// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvdyzcbvbkrssatlzmbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZHl6Y2J2Ymtyc3NhdGx6bWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mzk5NDIsImV4cCI6MjA2OTUxNTk0Mn0.84qLS3uKBo_VGonenB7NTTmlIEhfLHYzhaDSCqKv8mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});